### ISSUE TITLE
Filters and other downloadable not working on sunfish 

### ISSUE THREAD

**Issue by asterisk-ragavan** [reiryuki/Miui-Gallery-Magisk-Module#1]
Iam on android 12 beta port which has a device fingerprint of Google/sunfish 

Iam not able to download and kind of downloadable packs from the gallery

I have included my screen shot for your reference if needed ready to send logs
Thank you In advance

![Screenshot_20210701-232853](https://user-images.githubusercontent.com/75389172/124170151-b29cd580-dac4-11eb-9c47-3bad34259c8a.png)

![Screenshot_20210701-231649](https://user-images.githubusercontent.com/75389172/124169527-f4794c00-dac3-11eb-841c-da6c345ec77a.png)

**Comment by reiryuki** [comment]
Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, it will be closed immediately
