### ISSUE TITLE
Sim Card can't detected

### ISSUE THREAD

**Issue by PokeSaibott** [reiryuki/Miui-Gallery-Magisk-Module#2]
I use a Redmi Note 8 Pro and different Roms like Pixel Experience, Sakura Projekt ( based in letzter lineage OS) and now crdroid but when I activate this in magisk and restart my Phone my Sim Card are Note detected.

**Comment by reiryuki** [comment]
Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, it will be closed immediately

Try to read Troubleshootings and disable miui.features first
