### ISSUE TITLE
Gallery app closes immediately

### ISSUE THREAD

**Issue by Nacheras** [reiryuki/Miui-Gallery-Magisk-Module#3]
When I installed miui core and then the gallery magisk module, the app closes.
I´m not able to use it. I´m using latest versions both magisk modules.

**Comment by reiryuki** [comment]
I will never support 'talking only' without sending proper logs. If you want a fix, then read #bug_report carefully, and send required files to the author.

Support & Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, issues will be closed immediately

**Comment by Nacheras** [comment]
Okey thank you, don´t be angry with me I didn´t know this Telegram group
