### ISSUE TITLE
Miui gallery keeps crashing

### ISSUE THREAD

**Issue by NoelEldhoNommy** [reiryuki/Miui-Gallery-Magisk-Module#6]
Miui gallery keeps crashing for me whenever I open a picture in MIUI gallery

[magisk_log_2024-04-07T09.46.46.log](https://github.com/reiryuki/Miui-Gallery-Magisk-Module/files/14895759/magisk_log_2024-04-07T09.46.46.log)

This is the log file, please fix this isse as soon as possible. If you need further information, please don't hesitate to reply to me

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 5 stuffs:

1) Explanations ✓
2) Magisk/KernelSU install log if it's a Magisk module #magisk_install_log
3) Disable any other else modules (except the module you want to report, AML, dirac misoundfx Remover, AOSP soundfx Remover, & Sound Alive FX Remover Magisk Module. But if you are reporting for AML Ryuki Mod, then you need to enable all audio mod module you have.)
4) Full logcat #logcat
5) Z folder #zfolder

If you miss one of them, read #bug_report again https://t.me/androidryukimodsdiscussions/2618 please! If you got boot-loop, read #workarounds! If you don't understand, learning is the best you can do. Thank you.
